spring.application.name=auth-service

spring.config.import=optional:configserver:http://localhost:8888

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*

spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.secret=y1lgtSE5KRKLmjIsyz0t14Uz5Hbbty5ds0mR72fL3V8=
jwt.expiration=3600000